kind: Pod
apiVersion: v1
metadata:
  name: nginx-config
spec:
  containers:
  - name: nginx
    image: nginx
    # env:
    #   - name: course-1
    #     valueFrom:
    #       configMapKeyRef:
    #         name: expense-config
    #         key:  course
    envFrom:
    - configMapRef:
        name: expense-config